### PR TITLE
fix: adapt entrypoint to proper paths and checks for rc11 node & app qgb

### LINKED ISSUE #60: bridge node panic on v0.11.0-rc11
### Version of Git SHA

https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.11.0-rc11

### System OS

macOS

### Installed tools

_No response_

### Others

_No response_

### Steps to reproduce it

# Run local-celestia-devnet:

```bash
docker run --platform linux/amd64 -p 26657:26657 -p 26658:26658 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet:v0.11.0-rc11
```

# Clone Polaris:

```bash
git clone https://github.com/gupadhyaya/polaris.git
cd polaris
git checkout polaris
```

# Set auth token:
i’m using this as auth token, on rc11 devnet, but still getting same errors. ive manually set auth token and gotten same result

```bash
export AUTH_TOKEN=$(docker exec $(docker ps -q)  celestia bridge --node.store /bridge  auth admin)
```

Or change polaris/cosmos/init.sh AUTH_TOKEN to `AUTH_TOKEN=$(docker exec $(docker ps -q)  celestia bridge --node.store /bridge  auth admin)`

Or set it manually so that `AUTH_TOKEN="stringauthtoken"`

# Run polaris

```bash
mage start
```

### Expected result

posts to DA without an issue

### Actual result

https://gist.github.com/jcstein/722600b3c210f642dc1fe4635f837983 - devnet errors
https://app.warp.dev/block/11BIRPSaovIA0NkK7a6yqp - polaris errors

### Relevant log output

_No response_

### Notes

[Full logs here](https://app.warp.dev/block/YBkI5zkSA3HXnfPpHqqFOd)

### PR DESCRIPTION
**Pull request by Bidon15**
## Overview

- Adaptations with excluding --evm-address
- make paths variables that are visible for celestia user
- tested -> works fine 

Closes #60 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by jcstein — APPROVED** [review]
thank you @Bidon15 - LGTM

[building this PR (logs)](https://app.warp.dev/block/5r265cWijCN6S7iGa545F0) and [running the image (logs)](https://app.warp.dev/block/axTkWWZZhNw42ZFeiuSCZm), were both successful

**Comment by jcstein** [comment]
[not blocking] suggestion: update celestia-node to rc12 and celestia-app to rc14 in this PR, too

testing build on rc12 and rc14 ([logs](https://app.warp.dev/block/ac3TBbjrHOAdRpxd04RacV)), successful
running image from build ([logs](https://app.warp.dev/block/H7SXRzk7wejaMQ3bGYifbV)), successful

**Comment by jcstein** [comment]
[not blocking] 
The only thing that is wonky about the MsgRegisterEVMAddress in this setup, is that when the transaction is executed, the bridge node logs have the output from the transaction show up. regardless, it works as expected.

```terminal
6:21PM INF committed state app_hash=6E07DA870883408B025EC7F719112CFF28F90D4F698F8A06B3D8BB6AF258BF71 height=2 module=state num_txs=1
code: 0
codespace: ""
data: 12300A2E2F63656C65737469612E7167622E76312E4D7367526567697374657245564D41646472657373526573706F6E7365
events:
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: Y2VsZXN0aWExanJtNmswN2szcXA0c2s0N2hzdTVhd3ludmNndms4eTl1bnAwam0=
  - index: true
    key: YW1vdW50
    value: MzAwMDB1dGlh
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: Y2VsZXN0aWExN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxwbmpzM3M=
  - index: true
    key: YW1vdW50
    value: MzAwMDB1dGlh
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: Y2VsZXN0aWExN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxwbmpzM3M=
  - index: true
    key: c2VuZGVy
    value: Y2VsZXN0aWExanJtNmswN2szcXA0c2s0N2hzdTVhd3ludmNndms4eTl1bnAwam0=
  - index: true
    key: YW1vdW50
    value: MzAwMDB1dGlh
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: Y2VsZXN0aWExanJtNmswN2szcXA0c2s0N2hzdTVhd3ludmNndms4eTl1bnAwam0=
  type: message
- attributes:
  - index: true
    key: ZmVl
    value: MzAwMDB1dGlh
  - index: true
    key: ZmVlX3BheWVy
    value: Y2VsZXN0aWExanJtNmswN2szcXA0c2s0N2hzdTVhd3ludmNndms4eTl1bnAwam0=
  type: tx
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: Y2VsZXN0aWExanJtNmswN2szcXA0c2s0N2hzdTVhd3ludmNndms4eTl1bnAwam0vMQ==
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: bThyWFZrOUxYNld1dTJhaTlHVmN2TTdjWGNNS0xZUktEQVZtc081QmtaNTVZblFXMjlwSXc3cXBmQmlwNnN0cnlvdGRQOG1BQVg2YnpPS21lNWtMQ1E9PQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L2NlbGVzdGlhLnFnYi52MS5Nc2dSZWdpc3RlckVWTUFkZHJlc3M=
  type: message
gas_used: "66953"
gas_wanted: "210000"
height: "2"
info: ""
logs:
- events:
  - attributes:
    - key: action
      value: /celestia.qgb.v1.MsgRegisterEVMAddress
    type: message
  log: ""
  msg_index: 0
raw_log: '[{"msg_index":0,"events":[{"type":"message","attributes":[{"key":"action","value":"/celestia.qgb.v1.MsgRegisterEVMAddress"}]}]}]'
timestamp: ""
tx: null
txhash: B8EF98A22883B1BC745C15DF561C4B7D583CC7BE001F1F1D8845928A58F022A4
2023-09-11T18:21:31.272Z	INFO	header/store	store/store.go:361	new head	{"height": 2, "hash": "10B15DB039057C40CF3B3125A378C6D1609B02F87694A5E8006376604DB6A226"}
6:21PM INF indexed block exents height=2 module=txindex
```

**Comment by Bidon15** [comment]
@nashqueue and @gupadhyaya, can you please approve this PR? 

@jcstein I propose we do rc12 and rc14 in next PR 🙏 
As this PR is solely resolving the issue

**Review by nashqueue — APPROVED** [review]

**Comment by nashqueue** [comment]
Thank you !

**Pull request merged**
