### PR TITLE
entrypoint: echo rpc auth token for dev testing

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

This PR adds an `echo` for the node rpc auth token so that clients can use it for testing during development.

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by tuxcanfly** [comment]
For best practice, the container should mount keys from the host, e.g.:

`docker run -v $HOME/.celestia-light-mocha/keys:/bridge/keys local-celestia-devnet:latest`

**Comment by tzdybal** [comment]
I think users can simply `docker exec` to get the tokens :thinking:

**Comment by tzdybal** [comment]
But for debugging, playing around, etc, this echo might also be important.

**Review by jrmanes — APPROVED** [review]
LGTM!

**Review by Bidon15 — APPROVED** [review]

**Pull request merged**
