### PR TITLE
deps: update link to repo to rollkit & version

### PR DESCRIPTION
**Pull request by jcstein**
Update README.md

### CODE REVIEW

**Review by Bidon15 — APPROVED** [review]
LGTM

**Comment by jcstein** [comment]
I will merge when `local-celestia-devnet` tagged with 0.8.2 🫡

**Review by gupadhyaya — APPROVED** [review]

**Comment by smuu** [comment]
> I will merge when `local-celestia-devnet` tagged with 0.8.2 🫡

Release v0.8.2 is available and the corresponding container was pushed: https://github.com/rollkit/local-celestia-devnet/pkgs/container/local-celestia-devnet/83678716?tag=v0.8.2

**Review by smuu — APPROVED** [review]
LGTM

**Pull request merged**
